/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionstage;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author JUJU
 */
public class ConsulteOffre extends javax.swing.JFrame {

    private Espace_Etudiant e;
    private Connecter cnx = new Connecter();
    
    /**
     * Creates new form ConsulteOffre
     */
    
    private int index = 0;
    
    public ConsulteOffre()
    {
        
    }
    
    public ConsulteOffre(Espace_Etudiant e) {
        initComponents();
        this.e = e;
        affiche();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ville = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        domaine = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        libelle = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        datedebut = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        duree = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptif = new javax.swing.JTextArea();
        precedent = new javax.swing.JButton();
        fermer = new javax.swing.JButton();
        suivant = new javax.swing.JButton();
        postule = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Consultation des offres de stage");

        jLabel2.setText("Nom de l'entreprise");

        nom.setEditable(false);

        jLabel3.setText("Ville du stage");

        ville.setEditable(false);

        jLabel4.setText("Mail contact");

        mail.setEditable(false);

        jLabel5.setText("Domaine offre");

        domaine.setEditable(false);

        jLabel6.setText("Libellé de l'offre");

        libelle.setEditable(false);

        jLabel7.setText("Date de début du stage");

        datedebut.setEditable(false);

        jLabel8.setText("Durée du stage");

        duree.setEditable(false);

        jLabel9.setText("Descriptif de l'offre");

        descriptif.setEditable(false);
        descriptif.setColumns(20);
        descriptif.setRows(5);
        jScrollPane1.setViewportView(descriptif);

        precedent.setText("Precédent");
        precedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precedentActionPerformed(evt);
            }
        });

        fermer.setText("Fermer");
        fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermerActionPerformed(evt);
            }
        });

        suivant.setText("Suivant");
        suivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suivantActionPerformed(evt);
            }
        });

        postule.setText("Postuler");
        postule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postuleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(214, 214, 214))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(datedebut, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(duree, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(ville, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(domaine, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(58, 58, 58)
                            .addComponent(libelle, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(precedent)
                                    .addGap(74, 74, 74)
                                    .addComponent(postule)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(suivant))
                                .addComponent(jScrollPane1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fermer))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(ville, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(domaine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(libelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(datedebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(duree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(precedent)
                    .addComponent(suivant)
                    .addComponent(postule))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fermer))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerActionPerformed
        this.e.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_fermerActionPerformed

    private void suivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suivantActionPerformed
        lesuivant();
    }//GEN-LAST:event_suivantActionPerformed

    private void precedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precedentActionPerformed
        leprecedent();
    }//GEN-LAST:event_precedentActionPerformed

    private void postuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postuleActionPerformed
        postuler();
    }//GEN-LAST:event_postuleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsulteOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsulteOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsulteOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsulteOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsulteOffre().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField datedebut;
    private javax.swing.JTextArea descriptif;
    private javax.swing.JTextField domaine;
    private javax.swing.JTextField duree;
    private javax.swing.JButton fermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField libelle;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField nom;
    private javax.swing.JButton postule;
    private javax.swing.JButton precedent;
    private javax.swing.JButton suivant;
    private javax.swing.JTextField ville;
    // End of variables declaration//GEN-END:variables


    public List <OffreAconsulter> consultation()
    {
        
        Statement st,st2,st3;
        ResultSet rst,rst2,rst3;
        
        
        List <OffreAconsulter> listaconsulter = new ArrayList<>();
        
               
        try{
            st = cnx.ObtenirConnection().createStatement();
            st2 = cnx.ObtenirConnection().createStatement();
            
            rst = st.executeQuery("SELECT * FROM offre ");
            
            
            
            
            while(rst.next())
            {
                // On cherche les données dans la table entreprise 
                rst2 = st2.executeQuery("SELECT * FROM entreprise where nom ='"+rst.getString("nom")+"' ");
                
                while(rst2.next())
                {
                
                 listaconsulter.add(new OffreAconsulter(rst.getInt("id_of"),
                                                        rst2.getString("nom"),
                                                        rst2.getString("ville"),
                                                        rst2.getString("mail"),
                                                        rst.getString("domaine"),
                                                        rst.getString("libelle"),
                                                        rst.getString("datedebut"),
                                                        rst.getInt("duree"),
                                                        rst.getString("descriptif")));
                }
               
               
            }
        }
        catch (SQLException e){
            System.err.println(e);
            JOptionPane.showMessageDialog(null,"Erreur base de donnees");
        }
        
        return listaconsulter;
        
    }
    
    public void affiche ()
    {
        
        nom.setText(consultation().get(index).getNom());
        ville.setText(consultation().get(index).getVille());
        mail.setText(consultation().get(index).getMail());
        domaine.setText(consultation().get(index).getDomaine());
        libelle.setText(consultation().get(index).getLibelle());
        datedebut.setText(consultation().get(index).getDatedebut());
        duree.setText(Integer.toString(consultation().get(index).getDuree()));
        descriptif.setText(consultation().get(index).getDescriptif());
        
    }
    
    public void lesuivant()
    {
        index++;
        if (index > consultation().size() -1)
            index = 0;
        
        affiche();
    }
    
    public void leprecedent()
    {
        index--;
        if (index < 0)
            index = consultation().size() -1;
        
        affiche();
    }
    
    public void postuler()
    {
        Statement st;
        ResultSet rst;
        
        boolean bool = false;
        String rep = "";
        
        try{
            st = cnx.ObtenirConnection().createStatement();
            rst = st.executeQuery("SELECT * FROM postule");
            
            while(rst.next())
            {
                if ( (rst.getString("nom").equals(nom.getText()) ) && (rst.getString("user").equals(this.e.getuser())) && (rst.getInt("id_of") == consultation().get(index).getId()))
                    bool = true;
                
            }
            
            if (bool == true)
                    JOptionPane.showMessageDialog(null,"Vous avez probablement deja postule a cette offre");
                else
                {
                    try{
                        String query = "INSERT INTO postule (nom, user, id_of, reponse) VALUES ('"+nom.getText()+"','"+this.e.getuser()+"',"+consultation().get(index).getId()+",'"+rep+"')";
            
            
                       st.executeUpdate(query);
                       JOptionPane.showMessageDialog(null,"Votre candidature a bien été envoyé");
                       }
                   catch (SQLException e){
                        System.err.println(e);
                       }
                }
            
        }
        catch (SQLException e){
            System.err.println(e);
        }
    }
    
}

/*
 try{
            String query = "INSERT INTO postule (nom, user, id_of) VALUES ('"+nom.getText()+"','"+this.e.getuser()+"',"+consultation().get(index).getId()+")";
            
            st = cnx.ObtenirConnection().createStatement();
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"Votre candidature a bien été envoyé");
        }
        catch (SQLException e){
            System.err.println(e);
            JOptionPane.showMessageDialog(null,"Erreur base de donnees! Vous avez probablement deja postule a cette offre");
        }
 */