/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionstage;

/**
 *
 * @author JUJU
 */
public class Espace_Etudiant extends javax.swing.JFrame {

    private Main_Etudiant m;
    /**
     * Creates new form Espace_Etudiant
     */
    
    public Espace_Etudiant()
    {
        
    }
    
    public Espace_Etudiant(Main_Etudiant m) {
        initComponents();
        prenom_et.setText(m.getprenom());
        nom_et.setText(m.getnom());
        this.m = m;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        prenom_et = new javax.swing.JLabel();
        nom_et = new javax.swing.JLabel();
        mes_offres = new javax.swing.JButton();
        consultation = new javax.swing.JButton();
        deconnexion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Espace");

        prenom_et.setFont(new java.awt.Font("Ravie", 3, 14)); // NOI18N
        prenom_et.setText("jLabel2");

        nom_et.setFont(new java.awt.Font("Ravie", 3, 12)); // NOI18N
        nom_et.setText("jLabel3");

        mes_offres.setText("Mes offres");
        mes_offres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mes_offresActionPerformed(evt);
            }
        });

        consultation.setText("Consulter offres");
        consultation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultationActionPerformed(evt);
            }
        });

        deconnexion.setText("Deconnexion");
        deconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnexionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1)
                        .addGap(57, 57, 57)
                        .addComponent(prenom_et)
                        .addGap(44, 44, 44)
                        .addComponent(nom_et))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(deconnexion)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(consultation)
                        .addGap(171, 171, 171))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mes_offres)
                        .addGap(183, 183, 183))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(prenom_et)
                    .addComponent(nom_et))
                .addGap(88, 88, 88)
                .addComponent(mes_offres)
                .addGap(56, 56, 56)
                .addComponent(consultation)
                .addGap(58, 58, 58)
                .addComponent(deconnexion)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnexionActionPerformed
        new Main_Etudiant().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_deconnexionActionPerformed

    private void consultationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultationActionPerformed
        ConsulteOffre main =new ConsulteOffre(Espace_Etudiant.this);
        main.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_consultationActionPerformed

    private void mes_offresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mes_offresActionPerformed
        OffresEtudiant main =new OffresEtudiant(Espace_Etudiant.this);
        main.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_mes_offresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Espace_Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Espace_Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Espace_Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Espace_Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Espace_Etudiant().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultation;
    private javax.swing.JButton deconnexion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mes_offres;
    private javax.swing.JLabel nom_et;
    private javax.swing.JLabel prenom_et;
    // End of variables declaration//GEN-END:variables


    public String getnom ()
    {
        return this.m.getnom();
    }
    
    public String getprenom ()
    {
        return this.m.getprenom();
    }
    
    public String getuser ()
    {
        return this.m.getuser();
    }
    
}
