/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionstage;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author JUJU
 */
public class OffresEtudiant extends javax.swing.JFrame {

    private Espace_Etudiant e;
    private List <Integer> les_id_of;
    private Connecter cnx = new Connecter();
    /**
     * Creates new form OffresEtudiant
     */
    
    private int index = 0;
    
    public OffresEtudiant()
    {
        
    }
    
    public OffresEtudiant(Espace_Etudiant e) {
        initComponents();
        this.e = e;
        this.les_id_of = offres();
        affiche();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        datedebut = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        domaine = new javax.swing.JTextField();
        suivant = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        fermer = new javax.swing.JButton();
        libelle = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ville = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptif = new javax.swing.JTextArea();
        precedent = new javax.swing.JButton();
        duree = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        reponse = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setText("Durée du stage");

        datedebut.setEditable(false);

        jLabel6.setText("Libellé de l'offre");

        domaine.setEditable(false);

        suivant.setText("Suivant");
        suivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suivantActionPerformed(evt);
            }
        });

        jLabel7.setText("Date de début du stage");

        fermer.setText("Fermer");
        fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermerActionPerformed(evt);
            }
        });

        libelle.setEditable(false);

        jLabel1.setText("Mes offres");

        jLabel3.setText("Ville du stage");

        jLabel2.setText("Nom de l'entreprise");

        nom.setEditable(false);

        jLabel5.setText("Domaine offre");

        mail.setEditable(false);

        jLabel4.setText("Mail contact");

        ville.setEditable(false);

        jLabel9.setText("Descriptif de l'offre");

        descriptif.setEditable(false);
        descriptif.setColumns(20);
        descriptif.setRows(5);
        jScrollPane1.setViewportView(descriptif);

        precedent.setText("Precédent");
        precedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precedentActionPerformed(evt);
            }
        });

        duree.setEditable(false);

        jLabel10.setText("Reponse");

        reponse.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fermer))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(259, 259, 259))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(datedebut, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(duree, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(ville, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(domaine, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(58, 58, 58)
                            .addComponent(libelle, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(69, 69, 69)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(precedent)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(suivant)
                                    .addGap(103, 103, 103))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(reponse, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(ville, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(domaine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(libelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(datedebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(duree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(reponse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fermer)
                    .addComponent(precedent)
                    .addComponent(suivant)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void suivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suivantActionPerformed
        lesuivant();
    }//GEN-LAST:event_suivantActionPerformed

    private void fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerActionPerformed
        this.e.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_fermerActionPerformed

    private void precedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precedentActionPerformed
        leprecedent();
    }//GEN-LAST:event_precedentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OffresEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OffresEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OffresEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OffresEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OffresEtudiant().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField datedebut;
    private javax.swing.JTextArea descriptif;
    private javax.swing.JTextField domaine;
    private javax.swing.JTextField duree;
    private javax.swing.JButton fermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField libelle;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField nom;
    private javax.swing.JButton precedent;
    private javax.swing.JTextField reponse;
    private javax.swing.JButton suivant;
    private javax.swing.JTextField ville;
    // End of variables declaration//GEN-END:variables


    public List <Integer> offres()
    {
        Statement st;
        ResultSet rst;
        
        List <Integer> mes_id_of = new ArrayList<>();
        
        try{
            st = cnx.ObtenirConnection().createStatement();
            rst = st.executeQuery("SELECT * FROM postule where user= '"+this.e.getuser()+"' ");
            
            while(rst.next())
            {
                mes_id_of.add(new Integer(rst.getInt("id_of")));
            }
            
            
            
        }
        catch (SQLException e){
            System.err.println(e);
        }
        
        return mes_id_of;
    }

    
    
    public List <OffreAconsulter2> consultation()
    {
        
        Statement st,st2,st3;
        ResultSet rst,rst2,rst3;
        
        
        List <OffreAconsulter2> listaconsulter = new ArrayList<>();
        
               
        try{
            st = cnx.ObtenirConnection().createStatement();
            st2 = cnx.ObtenirConnection().createStatement();
            st3 = cnx.ObtenirConnection().createStatement();
            
            rst = st.executeQuery("SELECT * FROM offre ");
            
            
            
            
            while(rst.next())
            {
                
                for (Integer i : this.les_id_of)
                {
                if (i == rst.getInt("id_of"))
                {
                // On cherche les données dans la table entreprise 
                rst2 = st2.executeQuery("SELECT * FROM entreprise where nom ='"+rst.getString("nom")+"' ");
                rst3 = st3.executeQuery("SELECT * FROM postule where nom ='"+rst.getString("nom")+"' and  user ='"+this.e.getuser()+"' and id_of ="+i+" ");
                rst3.next();
                while(rst2.next())
                {
                
                 listaconsulter.add(new OffreAconsulter2(rst.getInt("id_of"),
                                                        rst2.getString("nom"),
                                                        rst2.getString("ville"),
                                                        rst2.getString("mail"),
                                                        rst.getString("domaine"),
                                                        rst.getString("libelle"),
                                                        rst.getString("datedebut"),
                                                        rst.getInt("duree"),
                                                        rst.getString("descriptif"),
                                                        rst3.getString("reponse")));
                }
               
                }
                }
               
            }
        }
        catch (SQLException e){
            System.err.println(e);
            JOptionPane.showMessageDialog(null,"Erreur base de donnees");
        }
        
        return listaconsulter;
        
    }
    
    public void affiche ()
    {
        
        if (consultation().size() == 0)
            JOptionPane.showMessageDialog(null,"Vous n'avez postulé a aucune offre");
        
        else
        {
            nom.setText(consultation().get(index).getNom());
            ville.setText(consultation().get(index).getVille());
            mail.setText(consultation().get(index).getMail());
            domaine.setText(consultation().get(index).getDomaine());
            libelle.setText(consultation().get(index).getLibelle());
            datedebut.setText(consultation().get(index).getDatedebut());
            duree.setText(Integer.toString(consultation().get(index).getDuree()));
            descriptif.setText(consultation().get(index).getDescriptif());
            reponse.setText(consultation().get(index).getReponse());
        }
        
        
        
    }
    
    public void lesuivant()
    {
        index++;
        if (index > consultation().size() -1)
            index = 0;
        
        affiche();
    }
    
    public void leprecedent()
    {
        index--;
        if (index < 0)
            index = consultation().size() -1;
        
        affiche();
    }
    
}
